---
- name: Create required directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: ubuntu
    group: ubuntu
  loop:
    - /home/ubuntu/monitoring
    - /home/ubuntu/traefik
    - /home/ubuntu/frontend
    - /home/ubuntu/backend

- name: Ensure acme.json file exists
  file:
    path: /home/ubuntu/traefik/acme.json
    state: touch
    owner: ubuntu
    group: ubuntu
    mode: '0600'
