name: Frontend CD Pipeline
run-name: ${{ github.actor }} triggered frontend pipeline

on:
  push:
    branches:
      - deployment
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    # environment:
    #   name: Frontend
    #   url: ${{ vars.URL }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare Frontend Environment
        env:
          FRONTEND_ENV: ${{ secrets.FRONTEND_ENV }}
        run: |
          echo "$FRONTEND_ENV" > frontend.env

      - name: Copy files to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: 
            - "frontend.env"
            - "compose.yml"
          target: "~/"

      - name: Use SSH Action
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            mv frontend.env frontend/.env
            docker compose up -d --no-deps --force-recreate frontend