name: CI Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - 'integration'
      
jobs:
  # Frontend Pipeline
  frontend-build-and-test:
    name: Frontend - Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' 

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Lint code
        run: |
          cd frontend
          npm run lint | tee /dev/null

      - name: Build
        run: |
          cd frontend
          npm run build

  frontend-build-push-image:
    name: Frontend - Build & Push Image
    runs-on: ubuntu-latest
    needs: frontend-build-and-test
    env:
      IMAGE_NAME: "${{ secrets.DOCKERHUB_USERNAME }}/frontend"
      IMAGE_TAG_1: "latest"
      IMAGE_TAG_2: "${{ github.run_number }}-${{ substring(github.sha, 0, 7) }}"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}  

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:frontend"
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG_1 }}, ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG_2 }}

  frontend-update-cd:
    name: Front Deploy Update
    runs-on: ubuntu-latest
    needs: frontend-build-push-image
    env:
      IMAGE_NAME: "${{ secrets.DOCKERHUB_USERNAME }}/frontend"
      IMAGE_TAG_2: "${{ github.run_number }}-${{ substring(github.sha, 0, 7) }}"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update Deployment YAML
        run: |
          sed -i "s|image: ${{ env.IMAGE_NAME }}:.*|image: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG_2 }}|" ./ansible/compose.yml.j2

      - name: Commit and Push Changes
        run: |
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_USER_NAME }}"
          git add ./k8s_manifest/deployment.yaml
          git commit -m "Update Docker Image Tag to ${{ env.IMAGE_TAG_2 }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

  # Backend Pipeline
  backend-build-and-test:
    name: Backend - Build & Test
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:13
        env:
          POSTGRES_USER: app
          POSTGRES_PASSWORD: changethis123
          POSTGRES_DB: app
          POSTGRES_HOST: localhost
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          cd backend
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install
          
      - name: Copy env file
        run: |
          cd backend
          cp .env.sample .env

      - name: Run app
        run: |
          cd backend
          poetry run bash ./prestart.sh
          poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000 &

      - name: Run tests
        run: |
          cd backend
          poetry run pytest | tee /dev/null


  backend-build-push-image:
    name: Backend - Build & Push Image
    runs-on: ubuntu-latest
    needs: backend-build-and-test
    env:
      IMAGE_NAME: "${{ secrets.DOCKERHUB_USERNAME }}/backend"
      IMAGE_TAG_1: "latest"
      IMAGE_TAG_2: "${{ github.run_number }}-${{ substring(github.sha, 0, 7) }}"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:backend"
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG_1 }}, ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG_2 }}


  backend-update-cd:
    name: Backend - Update CD Workflow
    runs-on: ubuntu-latest
    needs: backend-build-push-image
    env:
      IMAGE_NAME: "${{ secrets.DOCKERHUB_USERNAME }}/backend"
      IMAGE_TAG_2: "${{ github.run_number }}-${{ substring(github.sha, 0, 7) }}"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update Deployment YAML
        run: |
          sed -i "s|image: ${{ env.IMAGE_NAME }}:.*|image: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG_2 }}|" ./ansible/compose.yml.j2

      - name: Commit and Push Changes
        run: |
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_USER_NAME }}"
          git add ./k8s_manifest/deployment.yaml
          git commit -m "Update Docker Image Tag to ${{ env.IMAGE_TAG_2 }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}


